[package]
name = "pixle"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = "0.29"
wgpu = "0.19"
pollster = "0.3"
glam = "0.25"
egui = "0.26"
egui-winit = "0.26"
egui-wgpu = "0.26"
bytemuck = { version = "1.14", features = ["derive"] }
